/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'danie' at '12.11.16 12:18' with Gradle 3.0
 *
 * @author danie, @date 12.11.16 12:18
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
